# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'day2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 4'
  pod 'RxCocoa', '~> 4'
  pod 'RxAlamofire', '~> 4'
  # Pods for day2

end
